version: '4.11'

services:
  samba:
    build: .
    container_name: smb411
    environment:
      TZ: 'CST6CDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/samba:/etc/samba:ro
      - /var/lib/samba:/var/lib/samba
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      # - /share1:/share1
      # - /share2:/share2:ro  

networks:
  default:
